#!/bin/sh

# Just a small script to build the Elm app, and move files to the dist folder.

set -eu

# Commands will run relatively to root of the project
app_root="$(dirname "$(dirname "$(readlink "$0")")")"
cd "$app_root"

main() {
  create_clear_dist
  compile_elm
  copy_index
  copy_styles
  copy_images
}

create_clear_dist() {
    rm -rf dist-prod
    mkdir -p dist-prod/css
    mkdir -p dist-prod/dist
}

compile_elm() {
  node_modules/.bin/elm-make src/Main.elm --yes --output dist-prod/dist/main.js
}

copy_index() {
    cp index.html dist-prod/index.html
}

copy_styles() {
    cp css/tachyons.css dist-prod/css/tachyons.css
}

copy_images() {
    cp -r images dist-prod/images
}

main || exit 1
